const SUCCESS_COUNT = 3;
const MAX_RANDOM_NUM = 100;

const MIN_PROGRESSION_LENGTH = 5;
const MIN_STEP = 1;
const MAX_STEP = 5;
const MAX_START_RANDOM_NUM = 50;

const MAX_PROGRESSION_LENGTH = 9;

export {
  SUCCESS_COUNT,
  MAX_RANDOM_NUM,
  MIN_PROGRESSION_LENGTH,
  MIN_STEP,
  MAX_STEP,
  MAX_START_RANDOM_NUM,
  MAX_PROGRESSION_LENGTH,
};
